"""create category and news tables

Revision ID: 61bd52c65ec1
Revises: 618ac729cd4e
Create Date: 2025-09-18 14:50:14.946339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '61bd52c65ec1'
down_revision: Union[str, Sequence[str], None] = '618ac729cd4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.add_column('news', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'news', 'category', ['category_id'], ['id'])
    op.drop_column('news', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.drop_column('news', 'category_id')
    op.drop_table('category')
    # ### end Alembic commands ###
