from enum import Enum

class ErrorCode(str, Enum):
    SERVER_ERROR = "SERVER_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    ALREADY_EXISTS = "ALREADY_EXISTS"
    DATABASE_ERROR = "DATABASE_ERROR"